# Model
modelname: LinearInterpolation
modeltype: Classical
modelparams: {}

# Data
data_path: data/data/custom_3split
data_type: custom
data_load:
  train: false
  val: false
  test: true
  missingness:
    mimic_missingness:
      path: data/missingness_patterns/mHealth_missing_ecg

# Train
is_train: false
train:
  bs: 512
  gpus: [0]