# Model
modelname: Mean
modeltype: Classical
modelparams: {}

# Data
data_path: data/data/mimic_ppg
data_type: mimic_ppg
data_load:
  Mean: true
  bounds: 1
  train: false
  val: false
  test: true
  missingness:
    mimic_missingness:
      path: data/missingness_patterns/mHealth_missing_ppg

# Train
is_train: false
train:
  bs: 512
  gpus: [0]