# Model
modelname: FFT
modeltype: Classical
modelparams: {}

# Data
data_path: data/data/custom_3split
data_type: custom
data_load:
  train: false
  val: false
  test: true
  missingness:
    missingness_type: mimic # real
    split_type: test # remove
    addmissing: true # remove
    path: data/missingness_patterns
    # todo
    # mimic_missingness: 
    #   path: 

    # remove line 14 / type

    # later on -- >
    # base
    # -- child classes

    # registry


# Train
is_train: false


train: # experiment_params
  bs: 512
  gpus: [0]