# Model
modelname: FFT
modeltype: Classical
modelparams: {}

# Data
data_path: data/data/ptbxl_ecg
data_type: ptbxl
data_load:
  mode: true
  bounds: 1
  channels: [0]
  missingness: 
    extended_missingness:
      impute_extended: 100

# Train
is_train: false
train:
  bs: 128
  gpus: [0]