import os
naomi_britsgail_ppg= {'modelname':'naomi', "annotate":"_britsgail_mimic_ppg", 'modeltype':'naomi', 
            "data_name":"mimic_ppg",
            "data_load": {"mean":True, "bounds":1},
            "modelparams":{"params":{   'batch' : 2,
                                        'y_dim' : 1,
                                        'rnn_dim' : 300,
                                        'dec1_dim' : 200,
                                        'n_layers' : 2,
                                        'discrim_rnn_dim' : 128,
                                        'discrim_num_layers' : 1,
                                        'cuda' : True,
                                        'highest' : 1,
                                        'stochastic': False
                                    }, 
                "val_iters":10,"pretrain_iters":50,
                "clip" :10,
                "policy_learning_rate":1e-6, "discrim_learning_rate":1e-3,"pre_start_lr":1e-3,
                "pretrain_disc_iter" : 50, "max_iter_num":60000,
                "save_model_interval":100, "log_interval":100},
            "train":{"gpus":[0], "train_realppg":True}}

naomi_step256_ppg= {'modelname':'naomi', "annotate":"_step256_mimic_ppg", 'modeltype':'naomi', 
            "data_name":"mimic_ppg",
            "data_load": {"mean":True, "bounds":1},
            "modelparams":{"params":{   'batch' : 2,
                                        'y_dim' : 1,
                                        'rnn_dim' : 300,
                                        'dec1_dim' : 200,
                                        'dec2_dim' : 200,
                                        'dec4_dim' : 200,
                                        'dec8_dim' : 200,
                                        'dec16_dim' : 200,
                                        'dec32_dim' : 200,
                                        'dec64_dim' : 200,
                                        'dec128_dim' : 200,
                                        'dec256_dim' : 200,
                                        'dec512_dim' : 200,
                                        'n_layers' : 2,
                                        'discrim_rnn_dim' : 128,
                                        'discrim_num_layers' : 1,
                                        'cuda' : True,
                                        'highest' : 256,
                                        'stochastic': False
                                    }, 
                "val_iters":10,"pretrain_iters":50,
                "clip" :10,
                "policy_learning_rate":1e-6, "discrim_learning_rate":1e-3,"pre_start_lr":1e-3,
                "pretrain_disc_iter" : 50, "max_iter_num":60000,
                "save_model_interval":100, "log_interval":100},
            "train":{"gpus":[0], "train_realppg":True}}

naomi_step256_mimic_ecg= {'modelname':'naomi', "annotate":"_step256_mimic_ecg", 'modeltype':'naomi', 
            "data_name":"mimic_ecg",
            "data_load": {},
            "modelparams":{"params":{   'batch' : 2,
                                        'y_dim' : 1,
                                        'rnn_dim' : 300,
                                        'dec1_dim' : 200,
                                        'dec2_dim' : 200,
                                        'dec4_dim' : 200,
                                        'dec8_dim' : 200,
                                        'dec16_dim' : 200,
                                        'dec32_dim' : 200,
                                        'dec64_dim' : 200,
                                        'dec128_dim' : 200,
                                        'dec256_dim' : 200,
                                        'dec512_dim' : 200,
                                        'n_layers' : 2,
                                        'discrim_rnn_dim' : 128,
                                        'discrim_num_layers' : 1,
                                        'cuda' : True,
                                        'highest' : 256,
                                        'stochastic': False
                                    }, 
                "val_iters":10,"pretrain_iters":0,
                "reload_epoch":"pretrain",
                "pretrain_epochs":0,"clip" :10,
                "policy_learning_rate":1e-6, "discrim_learning_rate":1e-3,"pre_start_lr":1e-3,
                "pretrain_disc_iter" : 0, "max_iter_num":60000,
                "save_model_interval":500, "log_interval":100,
                "save_model_interval":100, "log_interval":10},
            "train":{"gpus":[0], "train_realecg":True}}

naomi_britsgail_mimic_ecg = {'modelname':'naomi', "annotate":"_britsgail_mimic_ecg", 'modeltype':'naomi', 
            "data_name":"mimic_ecg","data_load": {},
            "modelparams":{"params":{   'batch' : 2,
                                        'y_dim' : 1,
                                        'rnn_dim' : 300,
                                        'dec1_dim' : 200,
                                        'n_layers' : 2,
                                        'discrim_rnn_dim' : 128,
                                        'discrim_num_layers' : 1,
                                        'cuda' : True,
                                        'highest' : 1,
                                        'stochastic': False
                                    }, 
                "val_iters":10, "pretrain_iters":0,
                "reload_epoch":"pretrain",
                "pretrain_epochs":0,"clip" :10,
                "policy_learning_rate":1e-6, "discrim_learning_rate":1e-3,"pre_start_lr":1e-3,
                "pretrain_disc_iter" : 0, "max_iter_num":60000,
                "save_model_interval":500, "log_interval":100,
                "save_model_interval":100, "log_interval":10
                },
            "train":{"gpus":[0], "train_realecg":True}}


naomi_britsgail_transient_ptbxl = {'modelname':'naomi', "annotate":"_britsgail_transient_ptbxl", 'modeltype':'naomi', 
            "data_name":"ptbxl","data_load": {"mode":True, "bounds":1, "channels":[0]},
            "modelparams":{"params":{   'batch' : 64,
                                        'y_dim' : 1,
                                        'rnn_dim' : 300,
                                        'dec1_dim' : 200,
                                        'n_layers' : 2,
                                        'discrim_rnn_dim' : 128,
                                        'discrim_num_layers' : 1,
                                        'cuda' : True,
                                        'highest' : 1,
                                        'stochastic': False
                                    }, 
                "pretrain_epochs":20,"clip" :10,
                "policy_learning_rate":1e-6, "discrim_learning_rate":1e-3,"pre_start_lr":1e-3,
                "pretrain_disc_iter" : 2000, "max_iter_num":60000,
                "save_model_interval":500, "log_interval":100},
            "train":{"gpus":[0], "train_impute_wind":5, "train_impute_prob":.30}}


naomi_step64_transient_ptbxl = {'modelname':'naomi', "annotate":"_step64_transient_ptbxl", 'modeltype':'naomi', 
            "data_name":"ptbxl","data_load": {"mode":True, "bounds":1, "channels":[0]},
            "modelparams":{"params":{   'batch' : 64,
                                        'y_dim' : 1,
                                        'rnn_dim' : 300,
                                        'dec1_dim' : 200,
                                        'dec2_dim' : 200,
                                        'dec4_dim' : 200,
                                        'dec8_dim' : 200,
                                        'dec16_dim' : 200,
                                        'dec32_dim' : 200,
                                        'dec64_dim' : 200,
                                        'n_layers' : 2,
                                        'discrim_rnn_dim' : 128,
                                        'discrim_num_layers' : 1,
                                        'cuda' : True,
                                        'highest' : 64,
                                        'stochastic': False
                                    }, 
                "pretrain_epochs":20,"clip" :10,
                "policy_learning_rate":1e-6, "discrim_learning_rate":1e-3,"pre_start_lr":1e-3,
                "pretrain_disc_iter" : 2000, "max_iter_num":60000,
                "save_model_interval":500, "log_interval":100},
            "train":{"gpus":[0], "train_impute_wind":5, "train_impute_prob":.30}}



naomi_step256_extended_ptbxl = {'modelname':'naomi', "annotate":"_step256_extended_ptbxl", 'modeltype':'naomi', 
            "data_name":"ptbxl","data_load": {"mode":True, "bounds":1, "channels":[0]},
            "modelparams":{"params":{   'batch' : 64,
                                        'y_dim' : 1,
                                        'rnn_dim' : 300,
                                        'dec1_dim' : 200,
                                        'dec2_dim' : 200,
                                        'dec4_dim' : 200,
                                        'dec8_dim' : 200,
                                        'dec16_dim' : 200,
                                        'dec32_dim' : 200,
                                        'dec64_dim' : 200,
                                        'dec128_dim' : 200,
                                        'dec256_dim' : 200,
                                        'n_layers' : 2,
                                        'discrim_rnn_dim' : 128,
                                        'discrim_num_layers' : 1,
                                        'cuda' : True,
                                        'highest' : 256,
                                        'stochastic': False
                                    }, 
                "pretrain_epochs":20,"clip" :10,
                "policy_learning_rate":1e-6, "discrim_learning_rate":1e-3,"pre_start_lr":1e-3,
                "pretrain_disc_iter" : 2000, "max_iter_num":60000,
                "save_model_interval":500, "log_interval":100},
            "train":{"gpus":[0], "train_impute_extended":300}}


naomi_britsgail_extended_ptbxl = {'modelname':'naomi', "annotate":"_britsgail_extended_ptbxl", 'modeltype':'naomi', 
            "data_name":"ptbxl","data_load": {"mode":True, "bounds":1, "channels":[0]},
            "modelparams":{"params":{   'batch' : 64,
                                        'y_dim' : 1,
                                        'rnn_dim' : 300,
                                        'dec1_dim' : 200,
                                        'n_layers' : 2,
                                        'discrim_rnn_dim' : 128,
                                        'discrim_num_layers' : 1,
                                        'cuda' : True,
                                        'highest' : 1,
                                        'stochastic': False
                                    }, 
                "pretrain_epochs":20,"clip" :10,
                "policy_learning_rate":1e-6, "discrim_learning_rate":1e-3,"pre_start_lr":1e-3,
                "pretrain_disc_iter" : 2000, "max_iter_num":60000,
                "save_model_interval":500, "log_interval":100},
            "train":{"gpus":[0], "train_impute_extended":300}}
