# BDC MIMIC PPG Train
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  convertolong:
    attention_window: [800, 800]
    attention_dilation: [4, 4]

# Data
data_type: mimic_ppg
data_load:
  mean: true
  bounds: 1

# Train
is_train: true
train:
  iter_save: 100
  bs: 4
  gpus: [0, 1, 2, 3]
  train_realppg: true

----------------

# BDC MIMIC ECG Train
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  convertolong:
    attention_window: [800, 800]
    attention_dilation: [4, 4]

# Data
data_type: mimic_ecg
data_load: {}

# Train
is_train: true
train:
  iter_save: 100
  reload_epoch: pretrain
  bs: 4
  gpus: [0, 1, 2, 3]
  train_realecg: true

----------------

# BDC PTBXL Extended Train
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  max_len: 1000

# Data
data_type: ptbxl
data_load:
  mode: true
  bounds: 1
  channels: [0]

# Train
is_train: true
train:
  bs: 64
  gpus: [0, 1, 2]
  train_impute_extended: 300

----------------

# BDC PTBXL Packet Train
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  max_len: 1000

# Data
data_type: ptbxl
data_load:
  mode: true
  bounds: 1
  channels: [0]

# Train
is_train: true
train:
  bs: 64
  gpus: [0, 1, 2]
  train_impute_wind: 5
  train_impute_prob: 0.30

----------------

# BDC MIMIC PPG Test
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  convertolong:
    attention_window: [800, 800]
    attention_dilation: [4, 4]

# Data
data_type: mimic_ppg
data_load:
  addmissing: true
  mean: true
  bounds: 1
  train: false
  val: false
  test: true

# Train
is_train: false
train:
  iter_save: 100
  reload_epoch_long: 54200
  bs: 4
  gpus: [0]

----------------

# BDC MIMIC ECG Test
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  convertolong:
    attention_window: [800, 800]
    attention_dilation: [4, 4]

# Data
data_type: mimic_ecg
data_load:
  train: false
  val: false
  test: true
  addmissing: true

# Train
is_train: false
train:
  iter_save: 100
  reload_epoch_long: 47000
  bs: 4
  gpus: [0]

----------------

# BDC PTBXL Extended 10% Test
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  reload_epoch: best

# Data
data_type: ptbxl
data_load:
  mode: true
  bounds: 1
  impute_extended: 100
  channels: [0]

# Train
is_train: false
train:
  bs: 64
  gpus: [0]

----------------

# BDC PTBXL Extended 20% Test
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  reload_epoch: best

# Data
data_type: ptbxl
data_load:
  mode: true
  bounds: 1
  impute_extended: 200
  channels: [0]

# Train
is_train: false
train:
  bs: 64
  gpus: [0]

----------------

# BDC PTBXL Extended 30% Test
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  reload_epoch: best

# Data
data_type: ptbxl
data_load:
  mode: true
  bounds: 1
  impute_extended: 300
  channels: [0]

# Train
is_train: false
train:
  bs: 64
  gpus: [0]

----------------

# BDC PTBXL Extended 40% Test
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  reload_epoch: best

# Data
data_type: ptbxl
data_load:
  mode: true
  bounds: 1
  impute_extended: 400
  channels: [0]

# Train
is_train: false
train:
  bs: 64
  gpus: [0]

----------------

# BDC PTBXL Extended 50% Test
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  reload_epoch: best

# Data
data_type: ptbxl
data_load:
  mode: true
  bounds: 1
  impute_extended: 500
  channels: [0]

# Train
is_train: false
train:
  bs: 64
  gpus: [0]

----------------

# BDC PTBXL Transient 10% Test
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  reload_epoch: best

# Data
data_type: ptbxl
data_load:
  mode: true
  bounds: 1
  impute_transient:
    window: 5
    prob: 0.10
  channels: [0]

# Train
is_train: false
train:
  bs: 64
  gpus: [0]

----------------

# BDC PTBXL Transient 20% Test
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  reload_epoch: best

# Data
data_type: ptbxl
data_load:
  mode: true
  bounds: 1
  impute_transient:
    window: 5
    prob: 0.20
  channels: [0]

# Train
is_train: false
train:
  bs: 64
  gpus: [0]

----------------

# BDC PTBXL Transient 30% Test
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  reload_epoch: best

# Data
data_type: ptbxl
data_load:
  mode: true
  bounds: 1
  impute_transient:
    window: 5
    prob: 0.30
  channels: [0]

# Train
is_train: false
train:
  bs: 64
  gpus: [0]

----------------

# BDC PTBXL Transient 40% Test
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  reload_epoch: best

# Data
data_type: ptbxl
data_load:
  mode: true
  bounds: 1
  impute_transient:
    window: 5
    prob: 0.40
  channels: [0]

# Train
is_train: false
train:
  bs: 64
  gpus: [0, 1]

----------------

# BDC PTBXL Transient 50% Test
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  reload_epoch: best

# Data
data_type: ptbxl
data_load:
  mode: true
  bounds: 1
  impute_transient:
    window: 5
    prob: 0.50
  channels: [0]

# Train
is_train: false
train:
  bs: 64
  gpus: [0]

----------------

# BDC Custom PPG Train
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  convertolong:
    attention_window: [800, 800]
    attention_dilation: [4, 4]

# Data
data_type: custom_ppg
data_load:
  mean: true
  bounds: 1

# Train
is_train: true
train:
  iter_save: 100
  bs: 4
  gpus: [0, 1, 2, 3]
  train_realppg: true

----------------

# BDC Custom ECG Train
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  convertolong:
    attention_window: [800, 800]
    attention_dilation: [4, 4]

# Data
data_type: custom_ecg
data_load: {}

# Train
is_train: true
train:
  iter_save: 100
  reload_epoch: pretrain
  bs: 4
  gpus: [0, 1, 2, 3]
  train_realecg: true

----------------

# BDC Custom PTBXL Extended Train
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  max_len: 1000

# Data
data_type: custom_ptbxl
data_load:
  mode: true
  bounds: 1
  channels: [0]

# Train
is_train: true
train:
  bs: 64
  gpus: [0, 1, 2]
  train_impute_extended: 300

----------------

# BDC Custom PTBXL Transient Train
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  max_len: 1000

# Data
data_type: custom_ptbxl
data_load:
  mode: true
  bounds: 1
  channels: [0]

# Train
is_train: true
train:
  bs: 64
  gpus: [0, 1, 2]
  train_impute_wind: 5
  train_impute_prob: 0.30

----------------

# BDC Custom PPG Test
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  convertolong:
    attention_window: [800, 800]
    attention_dilation: [4, 4]

# Data
data_type: custom_ppg
data_load:
  addmissing: true
  mean: true
  bounds: 1
  train: false
  val: false
  test: true

# Train
is_train: false
train:
  iter_save: 100
  reload_epoch_long: 54200
  bs: 4
  gpus: [0]

----------------

# BDC Custom ECG Test
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  convertolong:
    attention_window: [800, 800]
    attention_dilation: [4, 4]

# Data
data_type: custom_ecg
data_load:
  train: false
  val: false
  test: true
  addmissing: true

# Train
is_train: false
train:
  iter_save: 100
  reload_epoch_long: 47000
  bs: 4
  gpus: [0]

----------------

# BDC Custom PTBXL Extended 10% Test
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  reload_epoch: best

# Data
data_type: custom_ptbxl
data_load:
  mode: true
  bounds: 1
  impute_extended: 100
  channels: [0]

# Train
is_train: false
train:
  bs: 64
  gpus: [0]

----------------

# BDC Custom PTBXL Extended 20% Test
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  reload_epoch: best

# Data
data_type: custom_ptbxl
data_load:
  mode: true
  bounds: 1
  impute_extended: 200
  channels: [0]

# Train
is_train: false
train:
  bs: 64
  gpus: [0]

----------------

# BDC Custom PTBXL Extended 30% Test
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  reload_epoch: best

# Data
data_type: custom_ptbxl
data_load:
  mode: true
  bounds: 1
  impute_extended: 300
  channels: [0]

# Train
is_train: false
train:
  bs: 64
  gpus: [0]

----------------

# BDC Custom PTBXL Extended 40% Test
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  reload_epoch: best

# Data
data_type: custom_ptbxl
data_load:
  mode: true
  bounds: 1
  impute_extended: 400
  channels: [0]

# Train
is_train: false
train:
  bs: 64
  gpus: [0]

----------------

# BDC Custom PTBXL Extended 50% Test
# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  reload_epoch: best

# Data
data_type: custom_ptbxl
data_load:
  mode: true
  bounds: 1
  impute_extended: 500
  channels: [0]

# Train
is_train: false
train:
  bs: 64
  gpus: [0]