# Model
modelname: BDCTransformer
modeltype: Transformer
modelparams:
  convertolong:
    attention_window: [800, 800]
    attention_dilation: [4, 4]

# Data
data_path: data/data/custom_ecg
data_type: custom_ecg
data_load:
  missingness:
    type: mimic
    data_type: ecg
    split_type: train
    addmissing: true
    path: data/missingness_patterns

# Train
is_train: true
train:
  iter_save: 100
  reload_epoch: pretrain
  bs: 4
  gpus: [0, 1, 2, 3]
  train_realecg: true